  repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
      - id: commitizen
        stages:
          - commit-msg

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        args:
          - --args=-json
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=./TFDOC.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
          - --hook-config=--add-to-exiting-file=true      # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
      - id: terraform_tflint
        args:
          - --args=--module
          - --args=--disable-rule=terraform_unused_required_providers
      - id: terraform_checkov
        args:
          - --args=--quiet
          - --args=--compact
          - --args=--soft-fail

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
        args: ['--fix=auto']
      - id: check-json
      - id: check-yaml

  #With bridgecrew
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '2.3.57' # change to tag or sha
    hooks:
      - id: checkov
        verbose: true
        args: [
          "-d", ".",
          "--skip-check", "CKV2_GHA_1",
        ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
